name: python-ml
channels:
  - defaults
dependencies:
  - _tflow_select=2.2.0=eigen
  - abseil-cpp=20211102.0=hc377ac9_0
  - absl-py=1.4.0=py311hca03da5_0
  - aiohttp=3.8.3=py311h80987f9_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - anyio=3.5.0=py311hca03da5_0
  - appnope=0.1.2=py311hca03da5_1001
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py311h80987f9_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - astunparse=1.6.3=py_0
  - async-timeout=4.0.2=py311hca03da5_0
  - attrs=22.1.0=py311hca03da5_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.12.2=py311hca03da5_0
  - blas=1.0=openblas
  - bleach=4.1.0=pyhd3eb1b0_0
  - blinker=1.4=py311hca03da5_0
  - blosc=1.21.3=h313beb8_0
  - boost-cpp=1.73.0=h1a28f6b_12
  - bottleneck=1.3.5=py311ha0d4635_0
  - brotli=1.0.9=h1a28f6b_7
  - brotli-bin=1.0.9=h1a28f6b_7
  - brotlipy=0.7.0=py311h80987f9_1002
  - brunsli=0.1=hc377ac9_1
  - bzip2=1.0.8=h620ffc9_4
  - c-ares=1.19.0=h80987f9_0
  - ca-certificates=2023.05.30=hca03da5_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - cairo=1.16.0=h302bd0f_5
  - certifi=2023.7.22=py311hca03da5_0
  - cffi=1.15.1=py311h80987f9_3
  - cfitsio=3.470=h7f6438f_7
  - chardet=4.0.0=py311hca03da5_1003
  - charls=2.2.0=hc377ac9_0
  - click=8.0.4=py311hca03da5_0
  - cloudpickle=2.2.1=py311hca03da5_0
  - comm=0.1.2=py311hca03da5_0
  - contourpy=1.0.5=py311h48ca7d4_0
  - cryptography=41.0.2=py311h6e31b35_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cytoolz=0.12.0=py311h80987f9_0
  - dask-core=2023.6.0=py311hca03da5_0
  - debugpy=1.6.7=py311h313beb8_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4=py311hca03da5_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.9=hc377ac9_0
  - flatbuffers=2.0.0=hc377ac9_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.1=hee714a5_2
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h1192e45_0
  - fribidi=1.0.10=h1a28f6b_0
  - frozenlist=1.3.3=py311h80987f9_0
  - fsspec=2023.4.0=py311hca03da5_0
  - gast=0.4.0=pyhd3eb1b0_0
  - gdk-pixbuf=2.42.10=h80987f9_0
  - gettext=0.21.0=h13f89a0_1
  - giflib=5.2.1=h80987f9_3
  - glib=2.69.1=h514c7bf_2
  - google-auth=2.6.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.5.2=py311hca03da5_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - graphite2=1.3.14=hc377ac9_1
  - graphviz=2.50.0=hf331ead_1
  - grpc-cpp=1.48.2=h877324c_0
  - grpcio=1.48.2=py311h877324c_0
  - gts=0.7.6=hde733a8_3
  - h5py=3.9.0=py311hba6ad2f_0
  - harfbuzz=4.3.0=he9eebac_1
  - hdf5=1.12.1=h160e8cb_2
  - icu=68.1=hc377ac9_0
  - idna=3.4=py311hca03da5_0
  - imagecodecs=2021.8.26=py311haa897ea_2
  - imageio=2.31.1=py311hca03da5_0
  - importlib-metadata=6.0.0=py311hca03da5_0
  - ipykernel=6.25.0=py311hb6e6a13_0
  - ipython=8.12.2=py311hca03da5_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=8.0.4=py311hca03da5_0
  - jedi=0.18.1=py311hca03da5_1
  - jinja2=3.1.2=py311hca03da5_0
  - joblib=1.2.0=py311hca03da5_0
  - jpeg=9e=h80987f9_1
  - jsonschema=4.17.3=py311hca03da5_0
  - jupyter_client=7.4.9=py311hca03da5_0
  - jupyter_core=5.3.0=py311hca03da5_0
  - jupyter_server=1.23.4=py311hca03da5_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=3.0.5=py311hca03da5_0
  - jxrlib=1.1=h1a28f6b_2
  - keras=2.12.0=py311hca03da5_0
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - kiwisolver=1.4.4=py311h313beb8_0
  - krb5=1.20.1=h8380606_1
  - lazy_loader=0.2=py311hca03da5_0
  - lcms2=2.12=hba8e193_0
  - lerc=3.0=hc377ac9_0
  - libaec=1.0.4=hc377ac9_1
  - libboost=1.73.0=h49e8a49_12
  - libbrotlicommon=1.0.9=h1a28f6b_7
  - libbrotlidec=1.0.9=h1a28f6b_7
  - libbrotlienc=1.0.9=h1a28f6b_7
  - libcurl=8.1.1=h0f1d93c_2
  - libcxx=14.0.6=h848a8c0_0
  - libdeflate=1.17=h80987f9_0
  - libedit=3.1.20221030=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libffi=3.4.4=hca03da5_0
  - libgd=2.3.3=h313beb8_2
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libiconv=1.16=h1a28f6b_2
  - libnghttp2=1.52.0=h10c0552_1
  - libopenblas=0.3.21=h269037a_0
  - libpng=1.6.39=h80987f9_0
  - libprotobuf=3.20.3=h514c7bf_0
  - librsvg=2.54.4=hb3bd4c3_3
  - libsodium=1.0.18=h1a28f6b_0
  - libssh2=1.10.0=h449679c_2
  - libtiff=4.5.0=h313beb8_2
  - libtool=2.4.6=h313beb8_1009
  - libwebp=1.2.4=ha3663a8_1
  - libwebp-base=1.2.4=h80987f9_1
  - libxml2=2.10.4=h372ba2a_0
  - libxslt=1.1.37=habca612_0
  - libzopfli=1.0.3=hc377ac9_0
  - llvm-openmp=14.0.6=hc6e5704_0
  - locket=1.0.0=py311hca03da5_0
  - lxml=4.9.2=py311h80987f9_0
  - lz4-c=1.9.4=h313beb8_0
  - markdown=3.4.1=py311hca03da5_0
  - markupsafe=2.1.1=py311h80987f9_0
  - matplotlib=3.7.1=py311hca03da5_1
  - matplotlib-base=3.7.1=py311h7aedaa7_1
  - matplotlib-inline=0.1.6=py311hca03da5_0
  - mistune=0.8.4=py311h80987f9_1000
  - multidict=6.0.2=py311h80987f9_0
  - munkres=1.1.4=py_0
  - nbclassic=0.5.5=py311hca03da5_0
  - nbclient=0.5.13=py311hca03da5_0
  - nbconvert=6.5.4=py311hca03da5_0
  - nbformat=5.7.0=py311hca03da5_0
  - ncurses=6.4=h313beb8_0
  - nest-asyncio=1.5.6=py311hca03da5_0
  - networkx=3.1=py311hca03da5_0
  - notebook=6.5.4=py311hca03da5_1
  - notebook-shim=0.2.2=py311hca03da5_0
  - nspr=4.35=h313beb8_0
  - nss=3.89.1=h313beb8_0
  - numexpr=2.8.4=py311h6dc990b_1
  - numpy=1.23.5=py311hb2c0538_0
  - numpy-base=1.23.5=py311h9eb1c70_0
  - oauthlib=3.2.2=py311hca03da5_0
  - openjpeg=2.3.0=h7a6adac_2
  - openssl=1.1.1v=h1a28f6b_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - packaging=23.0=py311hca03da5_0
  - pandas=2.0.3=py311h7aedaa7_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - pango=1.50.7=h7271ec9_0
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.2.0=pyhd3eb1b0_1
  - patsy=0.5.3=py311hca03da5_0
  - pcre=8.45=hc377ac9_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.4.0=py311h313beb8_0
  - pip=23.2.1=py311hca03da5_0
  - pixman=0.40.0=h1a28f6b_0
  - platformdirs=3.10.0=py311hca03da5_0
  - plotly=5.9.0=py311hca03da5_0
  - poppler=22.12.0=h497017c_0
  - poppler-data=0.4.11=hca03da5_1
  - prometheus_client=0.14.1=py311hca03da5_0
  - prompt-toolkit=3.0.36=py311hca03da5_0
  - protobuf=3.20.3=py311h313beb8_0
  - psutil=5.9.0=py311h80987f9_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py311hca03da5_1
  - pyjwt=2.4.0=py311hca03da5_0
  - pyopenssl=23.2.0=py311hca03da5_0
  - pyparsing=3.0.9=py311hca03da5_0
  - pyrsistent=0.18.0=py311h80987f9_0
  - pysocks=1.7.1=py311hca03da5_0
  - python=3.11.4=hc0d8a6c_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py311hca03da5_0
  - python-flatbuffers=2.0=pyhd3eb1b0_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytz=2022.7=py311hca03da5_0
  - pywavelets=1.4.1=py311h80987f9_0
  - pyyaml=6.0=py311h80987f9_1
  - pyzmq=23.2.0=py311h313beb8_0
  - re2=2022.04.01=hc377ac9_0
  - readline=8.2=h1a28f6b_0
  - requests=2.31.0=py311hca03da5_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scikit-image=0.20.0=py311h313beb8_0
  - scikit-learn=1.2.2=py311h313beb8_1
  - scipy=1.11.1=py311hc76d9b0_0
  - seaborn=0.12.2=py311hca03da5_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=68.0.0=py311hca03da5_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.9=hc377ac9_0
  - sniffio=1.2.0=py311hca03da5_1
  - soupsieve=2.4=py311hca03da5_0
  - sqlite=3.41.2=h80987f9_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - statsmodels=0.14.0=py311hb9f6ed7_0
  - tenacity=8.2.2=py311hca03da5_0
  - tensorboard=2.12.1=py311hca03da5_0
  - tensorboard-data-server=0.7.0=py311ha6e5c4f_0
  - tensorboard-plugin-wit=1.8.1=py311hca03da5_0
  - tensorflow=2.12.0=eigen_py311h689d69b_0
  - tensorflow-base=2.12.0=eigen_py311h0a52ebb_0
  - tensorflow-estimator=2.12.0=py311hca03da5_0
  - termcolor=2.1.0=py311hca03da5_0
  - terminado=0.17.1=py311hca03da5_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tifffile=2021.7.2=pyhd3eb1b0_2
  - tinycss2=1.2.1=py311hca03da5_0
  - tk=8.6.12=hb8d0fd4_0
  - toolz=0.12.0=py311hca03da5_0
  - tornado=6.3.2=py311h80987f9_0
  - traitlets=5.7.1=py311hca03da5_0
  - treelib=1.6.1=pyhd3eb1b0_0
  - typing-extensions=4.7.1=py311hca03da5_0
  - typing_extensions=4.7.1=py311hca03da5_0
  - tzdata=2023c=h04d1e81_0
  - urllib3=1.26.16=py311hca03da5_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py311hca03da5_1
  - websocket-client=0.58.0=py311hca03da5_4
  - werkzeug=2.2.3=py311hca03da5_0
  - wheel=0.35.1=pyhd3eb1b0_0
  - widgetsnbextension=4.0.5=py311hca03da5_0
  - wrapt=1.14.1=py311h80987f9_0
  - xlrd=2.0.1=pyhd3eb1b0_1
  - xz=5.4.2=h80987f9_0
  - yaml=0.2.5=h1a28f6b_0
  - yarl=1.8.1=py311h80987f9_0
  - zeromq=4.3.4=hc377ac9_0
  - zfp=0.5.5=hc377ac9_6
  - zipp=3.11.0=py311hca03da5_0
  - zlib=1.2.13=h5a0b063_0
  - zstd=1.5.5=hd90d995_0
  - pip:
      - array-record==0.4.1
      - brewer2mpl==1.4.1
      - charset-normalizer==3.2.0
      - chart-studio==1.1.0
      - dm-tree==0.1.8
      - etils==1.4.1
      - ggplot==0.11.5
      - googleapis-common-protos==1.60.0
      - importlib-resources==6.0.1
      - promise==2.3
      - pyclust==0.2.0
      - python-graphviz==0.20.1
      - retrying==1.3.4
      - tensorflow-datasets==4.9.2
      - tensorflow-metadata==1.14.0
      - toml==0.10.2
      - tqdm==4.66.1
