name: environment_P38
channels:
  - defaults
dependencies:
  - argon2-cffi=20.1.0=py38he774522_1
  - async_generator=1.10=py_0
  - attrs=20.2.0=py_0
  - backcall=0.2.0=py_0
  - bleach=3.2.1=py_0
  - ca-certificates=2020.10.14=0
  - certifi=2020.6.20=py38_0
  - cffi=1.14.3=py38h7a1dbc1_0
  - colorama=0.4.3=py_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py38_0
  - importlib-metadata=2.0.0=py_1
  - importlib_metadata=2.0.0=1
  - ipykernel=5.3.4=py38h5ca1d4c_0
  - ipython=7.18.1=py38h5ca1d4c_0
  - ipython_genutils=0.2.0=py38_0
  - jedi=0.17.2=py38_0
  - jinja2=2.11.2=py_0
  - jsonschema=3.2.0=py_2
  - jupyter_client=6.1.7=py_0
  - jupyter_core=4.6.3=py38_0
  - jupyterlab_pygments=0.1.2=py_0
  - libsodium=1.0.18=h62dcd97_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=1.1.1=py38he774522_0
  - mistune=0.8.4=py38he774522_1000
  - msys2-conda-epoch=20160418=1
  - nbclient=0.5.1=py_0
  - nbconvert=6.0.7=py38_0
  - nbformat=5.0.8=py_0
  - nest-asyncio=1.4.1=py_0
  - notebook=6.1.4=py38_0
  - openssl=1.1.1h=he774522_0
  - packaging=20.4=py_0
  - pandoc=2.11=h9490d1a_0
  - pandocfilters=1.4.2=py38_1
  - parso=0.7.0=py_0
  - pickleshare=0.7.5=py38_1000
  - pip=20.2.3=py38_0
  - prometheus_client=0.8.0=py_0
  - prompt-toolkit=3.0.8=py_0
  - pycparser=2.20=py_2
  - pygments=2.7.1=py_0
  - pyparsing=2.4.7=py_0
  - pyrsistent=0.17.3=py38he774522_0
  - python=3.8.5=h5fd99cc_1
  - python-dateutil=2.8.1=py_0
  - pywin32=227=py38he774522_1
  - pywinpty=0.5.7=py38_0
  - pyzmq=19.0.2=py38ha925a31_1
  - send2trash=1.5.0=py38_0
  - setuptools=50.3.0=py38h9490d1a_1
  - six=1.15.0=py_0
  - sqlite=3.33.0=h2a8f88b_0
  - terminado=0.9.1=py38_0
  - testpath=0.4.4=py_0
  - tornado=6.0.4=py38he774522_1
  - traitlets=5.0.5=py_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_3
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py38_1
  - wheel=0.35.1=py_0
  - wincertstore=0.2=py38_0
  - winpty=0.4.3=4
  - zeromq=4.3.2=ha925a31_3
  - zipp=3.3.0=py_0
  - zlib=1.2.11=h62dcd97_4
prefix: C:\Users\TOSHIBA\.conda\envs\environment_P38
