name: python-ml-2020
channels:
  - conda-forge
  - defaults
dependencies:
  - absl-py=0.5.0=py_0
  - appnope=0.1.0=py35_0
  - astor=0.7.1=py_0
  - backcall=0.1.0=py_0
  - blas=1.1=openblas
  - bleach=3.1.5=pyh9f0ad1d_0
  - brewer2mpl=1.4.1=py_3
  - bzip2=1.0.8=h0b31af3_2
  - c-ares=1.15.0=h01d97ff_1001
  - ca-certificates=2020.4.5.1=hecc5488_0
  - certifi=2018.8.24=py35_1001
  - cloudpickle=1.4.1=py_0
  - cycler=0.10.0=py_2
  - dask-core=2.6.0=py_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.2.3=py35_2
  - freetype=2.8.1=hfa320df_1
  - gast=0.3.3=py_0
  - ggplot=0.11.5=py_4
  - grpcio=1.14.1=py35hd60e7a3_0
  - imageio=2.8.0=py_0
  - ipykernel=5.1.0=pyh24bf2e0_0
  - ipython=7.0.1=py35h24bf2e0_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.12.1=py35_0
  - jinja2=2.11.2=pyh9f0ad1d_0
  - jpeg=9c=h1de35cc_1001
  - json5=0.9.0=py_0
  - jsonschema=2.6.0=py35_2
  - jupyter_client=5.3.3=py_0
  - jupyter_core=4.5.0=py_0
  - jupyterlab=2.1.0=py_0
  - jupyterlab_server=1.0.0=py_0
  - libcxx=10.0.0=h1af66ff_2
  - libffi=3.2.1=h4a8c4bd_1007
  - libgfortran=3.0.1=0
  - libpng=1.6.37=hbbe82c9_1
  - libprotobuf=3.6.0=hd9629dc_1000
  - libsodium=1.0.18=h01d97ff_0
  - libtiff=4.1.0=h2ae36a8_6
  - libwebp-base=1.1.0=h0b31af3_3
  - lz4-c=1.9.2=h4a8c4bd_1
  - markdown=3.2.1=py_0
  - markupsafe=1.0=py35h470a237_1
  - matplotlib=2.1.2=py35h6d6146d_0
  - mistune=0.8.3=py35h470a237_2
  - nbconvert=5.6.0=py_0
  - nbformat=5.0.6=py_0
  - ncurses=6.1=h0a44026_1002
  - networkx=2.4=py_1
  - notebook=5.7.0=py35_0
  - numpy=1.14.6=py35_blas_openblashd3ea46f_200
  - olefile=0.46=py_0
  - openblas=0.2.20=8
  - openssl=1.0.2u=h0b31af3_0
  - packaging=20.4=pyh9f0ad1d_0
  - pandas=0.22.0=py35_1
  - pandoc=2.9.2.1=0
  - pandocfilters=1.4.2=py_1
  - parso=0.7.0=pyh9f0ad1d_0
  - patsy=0.5.1=py_0
  - pexpect=4.6.0=py35_0
  - pickleshare=0.7.5=py35_0
  - pillow=5.2.0=py35h2dc6135_1
  - pip=20.1.1=py_1
  - plotly=2.7.0=py35_0
  - prometheus_client=0.8.0=pyh9f0ad1d_0
  - prompt_toolkit=2.0.10=py_0
  - protobuf=3.6.0=py35hfc679d8_0
  - ptyprocess=0.6.0=py_1001
  - pygments=2.6.1=py_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - python=3.5.5=h5001a0f_2
  - python-dateutil=2.8.1=py_0
  - pytz=2020.1=pyh9f0ad1d_0
  - pywavelets=1.0.1=py35h7eb728f_0
  - pyzmq=17.1.2=py35hae99301_0
  - readline=7.0=hcfe32e1_1001
  - requests=2.12.5=py35_0
  - scikit-image=0.14.0=py35hfc679d8_1
  - scikit-learn=0.20.0=py35_blas_openblasha84fab4_201
  - scipy=1.1.0=py35_blas_openblash7943236_201
  - send2trash=1.5.0=py_0
  - setuptools=40.4.3=py35_0
  - simplegeneric=0.8.1=py_1
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.28.0=h9721f7c_0
  - statsmodels=0.9.0=py35_0
  - tensorboard=1.10.0=py35_0
  - tensorflow=1.10.0=py35_0
  - termcolor=1.1.0=py_2
  - terminado=0.8.1=py35_1
  - testpath=0.4.4=py_0
  - tk=8.6.10=hbbe82c9_0
  - toolz=0.10.0=py_0
  - tornado=5.1.1=py35h470a237_0
  - traitlets=4.3.2=py35_0
  - wcwidth=0.1.9=pyh9f0ad1d_0
  - webencodings=0.5.1=py_1
  - werkzeug=1.0.1=pyh9f0ad1d_0
  - wheel=0.34.2=py_1
  - xz=5.2.5=h0b31af3_0
  - zeromq=4.2.5=hfc679d8_4
  - zlib=1.2.11=h0b31af3_1006
  - zstd=1.4.4=h4b3e974_3
  - pip:
    - attrs==19.3.0
    - cffi==1.14.0
    - future==0.18.2
    - importlib-metadata==1.6.0
    - ipywidgets==7.5.1
    - more-itertools==8.3.0
    - pathlib2==2.3.5
    - pluggy==0.13.1
    - py==1.8.1
    - pyclust==0.2.0
    - pycparser==2.20
    - pytest==5.4.2
    - python-graphviz==0.14
    - seaborn==0.9.1
    - treelib==1.6.1
    - tzlocal==2.1
    - widgetsnbextension==3.5.1
    - zipp==1.2.0
prefix: /opt/anaconda3/envs/python-ml-2020

